# Generated by Django 3.0.3 on 2020-03-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='home_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='second_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='street',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
