# Generated by Django 3.0.3 on 2020-03-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200326_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='city_html',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
