# Generated by Django 3.0.3 on 2020-03-26 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_info_city_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='city_html',
        ),
    ]
