# Generated by Django 3.0.3 on 2020-03-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_info_city_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
