# Generated by Django 3.0.3 on 2020-03-30 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_info_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.User'),
        ),
    ]
