# Generated by Django 3.0.3 on 2020-03-30 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200331_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='image',
        ),
    ]
