# Generated by Django 3.0.3 on 2020-03-31 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_info_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='user',
        ),
    ]
