# Generated by Django 3.0.3 on 2020-03-31 12:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0016_auto_20200331_1538'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Info',
            new_name='PersonalInfo',
        ),
    ]
