# Generated by Django 3.0.3 on 2020-03-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20200331_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='NehasimModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('home_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
