# Generated by Django 3.0.3 on 2020-04-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_payment_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='cc_expiry',
        ),
        migrations.AddField(
            model_name='payment',
            name='CardholderName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='Year',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
