# Generated by Django 3.0.3 on 2020-04-01 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20200401_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='Month',
            new_name='Expiration_Date',
        ),
    ]
